"""cms tables

Revision ID: 54ec850d51ae
Revises: 7c9e6b2eb1b4
Create Date: 2026-06-15 12:54:04.161236

"""
# flake8: noqa
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ec850d51ae'
down_revision = '7c9e6b2eb1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berichte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('veroeffentlicht', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_berichte'))
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('inhalt', sa.Text(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('veroeffentlicht', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news'))
    )
    op.create_table('termine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=120), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('uhrzeit', sa.String(length=20), nullable=True),
    sa.Column('ort', sa.String(length=200), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('veroeffentlicht', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_termine'))
    )
    op.create_table('vorstand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('funktion', sa.String(length=120), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('spruch', sa.Text(), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('sichtbar', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vorstand'))
    )
    op.create_table('bericht_bilder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bericht_id', sa.Integer(), nullable=False),
    sa.Column('dateiname', sa.String(length=255), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bericht_id'], ['berichte.id'], name=op.f('fk_bericht_bilder_bericht_id_berichte')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bericht_bilder'))
    )
    # Hinweis: Etwaige Alembic-Autogenerate-Anpassungen an der
    # bestehenden 'users'-Tabelle wurden bewusst entfernt – diese
    # Migration legt ausschließlich die fünf neuen CMS-Tabellen an.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bericht_bilder')
    op.drop_table('vorstand')
    op.drop_table('termine')
    op.drop_table('news')
    op.drop_table('berichte')
    # ### end Alembic commands ###
