"""drop news table

Revision ID: d538194e54b4
Revises: 54ec850d51ae
Create Date: 2026-06-20 21:09:05.885090

"""
# flake8: noqa
# Autogenerierte Alembic-Migrationen folgen nicht den PEP8-
# Continuation-Regeln; daher vom Lint ausgenommen.
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd538194e54b4'
down_revision = '54ec850d51ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titel', sa.VARCHAR(length=200), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=True),
    sa.Column('inhalt', sa.TEXT(), nullable=True),
    sa.Column('datum', sa.DATE(), nullable=True),
    sa.Column('veroeffentlicht', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news'))
    )
    # ### end Alembic commands ###
